AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: International Cup Pairings Reveal System

Parameters:
  AdminPassword:
    Type: String
    Default: icup2024
    NoEcho: true
    Description: Password for admin access to pairing management
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - staging
    Description: Environment name for resource naming (prod or staging)

Resources:
  # Lambda Execution Role
  PairingsLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchWriteItem
                Resource:
                  - !Sub 'arn:aws:dynamodb:us-east-1:*:table/icup-pairings-${Environment}'
                  - !Sub 'arn:aws:dynamodb:us-east-1:*:table/icup-reveal-state-${Environment}'
                  - !Sub 'arn:aws:dynamodb:us-east-1:*:table/icup-websocket-connections-${Environment}'
                  - !Sub 'arn:aws:dynamodb:us-east-1:*:table/icup-players-${Environment}'
                  - !Sub 'arn:aws:dynamodb:us-east-1:*:table/icup-betslips-${Environment}'
        - PolicyName: APIGatewayManageConnections
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - execute-api:ManageConnections
                Resource: '*'

  # DynamoDB Tables
  
  # Players Table
  PlayersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'icup-players-${Environment}'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  
  # Pairings Table
  PairingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'icup-pairings-${Environment}'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  
  # Reveal State Table
  RevealStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'icup-reveal-state-${Environment}'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  
  # WebSocket Connections Table
  WebSocketConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'icup-websocket-connections-${Environment}'
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # Betslips Table
  BetslipsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'icup-betslips-${Environment}'
      AttributeDefinitions:
        - AttributeName: betslipId
          AttributeType: S
      KeySchema:
        - AttributeName: betslipId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # Lambda Functions
  GetPairingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/getPairings/
      Handler: index.handler
      Runtime: nodejs18.x
      Role: !GetAtt PairingsLambdaRole.Arn
      Timeout: 10
      Environment:
        Variables:
          PAIRINGS_TABLE: !Sub 'icup-pairings-${Environment}'
          REVEAL_STATE_TABLE: !Sub 'icup-reveal-state-${Environment}'
          PLAYERS_TABLE: !Sub 'icup-players-${Environment}'
          WEBSOCKET_TABLE: !Sub 'icup-websocket-connections-${Environment}'
      Events:
        GetPairings:
          Type: Api
          Properties:
            RestApiId: !Ref PairingsApi
            Path: /pairings
            Method: GET

  UpdatePairingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/updatePairings/
      Handler: index.handler
      Runtime: nodejs18.x
      Role: !GetAtt PairingsLambdaRole.Arn
      Timeout: 30
      Environment:
        Variables:
          ADMIN_PASSWORD: !Ref AdminPassword
          PAIRINGS_TABLE: !Sub 'icup-pairings-${Environment}'
          REVEAL_STATE_TABLE: !Sub 'icup-reveal-state-${Environment}'
          PLAYERS_TABLE: !Sub 'icup-players-${Environment}'
          WEBSOCKET_TABLE: !Sub 'icup-websocket-connections-${Environment}'
      Events:
        UpdatePairings:
          Type: Api
          Properties:
            RestApiId: !Ref PairingsApi
            Path: /pairings
            Method: POST

  GetPlayersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/getPlayers/
      Handler: index.handler
      Runtime: nodejs18.x
      Role: !GetAtt PairingsLambdaRole.Arn
      Timeout: 10
      Environment:
        Variables:
          PAIRINGS_TABLE: !Sub 'icup-pairings-${Environment}'
          REVEAL_STATE_TABLE: !Sub 'icup-reveal-state-${Environment}'
          PLAYERS_TABLE: !Sub 'icup-players-${Environment}'
          WEBSOCKET_TABLE: !Sub 'icup-websocket-connections-${Environment}'
      Events:
        GetPlayers:
          Type: Api
          Properties:
            RestApiId: !Ref PairingsApi
            Path: /players
            Method: GET

  UpdatePlayersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/updatePlayers/
      Handler: index.handler
      Runtime: nodejs18.x
      Role: !GetAtt PairingsLambdaRole.Arn
      Timeout: 30
      Environment:
        Variables:
          ADMIN_PASSWORD: !Ref AdminPassword
          PAIRINGS_TABLE: !Sub 'icup-pairings-${Environment}'
          REVEAL_STATE_TABLE: !Sub 'icup-reveal-state-${Environment}'
          PLAYERS_TABLE: !Sub 'icup-players-${Environment}'
          WEBSOCKET_TABLE: !Sub 'icup-websocket-connections-${Environment}'
      Events:
        UpdatePlayers:
          Type: Api
          Properties:
            RestApiId: !Ref PairingsApi
            Path: /players
            Method: POST

  RevealPairingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/revealPairing/
      Handler: index.handler
      Runtime: nodejs18.x
      Role: !GetAtt PairingsLambdaRole.Arn
      Timeout: 30
      Environment:
        Variables:
          ADMIN_PASSWORD: !Ref AdminPassword
          WEBSOCKET_ENDPOINT: !Sub 'https://${PairingsWebSocket}.execute-api.${AWS::Region}.amazonaws.com/prod'
          PAIRINGS_TABLE: !Sub 'icup-pairings-${Environment}'
          REVEAL_STATE_TABLE: !Sub 'icup-reveal-state-${Environment}'
          PLAYERS_TABLE: !Sub 'icup-players-${Environment}'
          WEBSOCKET_TABLE: !Sub 'icup-websocket-connections-${Environment}'
      Events:
        RevealPairing:
          Type: Api
          Properties:
            RestApiId: !Ref PairingsApi
            Path: /reveal
            Method: POST

  WebSocketConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/websocketConnect/
      Handler: index.handler
      Runtime: nodejs18.x
      Role: !GetAtt PairingsLambdaRole.Arn
      Timeout: 10
      Environment:
        Variables:
          PAIRINGS_TABLE: !Sub 'icup-pairings-${Environment}'
          REVEAL_STATE_TABLE: !Sub 'icup-reveal-state-${Environment}'
          PLAYERS_TABLE: !Sub 'icup-players-${Environment}'
          WEBSOCKET_TABLE: !Sub 'icup-websocket-connections-${Environment}'

  WebSocketDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/websocketDisconnect/
      Handler: index.handler
      Runtime: nodejs18.x
      Role: !GetAtt PairingsLambdaRole.Arn
      Timeout: 10
      Environment:
        Variables:
          PAIRINGS_TABLE: !Sub 'icup-pairings-${Environment}'
          REVEAL_STATE_TABLE: !Sub 'icup-reveal-state-${Environment}'
          PLAYERS_TABLE: !Sub 'icup-players-${Environment}'
          WEBSOCKET_TABLE: !Sub 'icup-websocket-connections-${Environment}'

  GooglePhotosProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/googlePhotosProxy/
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30
      Events:
        GetPhotos:
          Type: Api
          Properties:
            RestApiId: !Ref PairingsApi
            Path: /google-photos
            Method: GET

  CreateBetslipFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/createBetslip/
      Handler: index.handler
      Runtime: nodejs18.x
      Role: !GetAtt PairingsLambdaRole.Arn
      Timeout: 10
      Environment:
        Variables:
          BETSLIPS_TABLE: !Sub 'icup-betslips-${Environment}'
      Events:
        CreateBetslip:
          Type: Api
          Properties:
            RestApiId: !Ref PairingsApi
            Path: /betslips
            Method: POST

  GetBetslipsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/getBetslips/
      Handler: index.handler
      Runtime: nodejs18.x
      Role: !GetAtt PairingsLambdaRole.Arn
      Timeout: 10
      Environment:
        Variables:
          BETSLIPS_TABLE: !Sub 'icup-betslips-${Environment}'
          ADMIN_PASSWORD: !Ref AdminPassword
      Events:
        GetBetslips:
          Type: Api
          Properties:
            RestApiId: !Ref PairingsApi
            Path: /betslips
            Method: GET

  UpdateBetslipFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/updateBetslip/
      Handler: index.handler
      Runtime: nodejs18.x
      Role: !GetAtt PairingsLambdaRole.Arn
      Timeout: 10
      Environment:
        Variables:
          BETSLIPS_TABLE: !Sub 'icup-betslips-${Environment}'
          ADMIN_PASSWORD: !Ref AdminPassword
      Events:
        UpdateBetslip:
          Type: Api
          Properties:
            RestApiId: !Ref PairingsApi
            Path: /betslips/{id}
            Method: PUT

  # REST API
  PairingsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Admin-Password'"
        AllowOrigin: "'*'"

  # WebSocket API
  PairingsWebSocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: icup-pairings-websocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action

  WebSocketConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PairingsWebSocket
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Join
        - /
        - - integrations
          - !Ref WebSocketConnectIntegration

  WebSocketDisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PairingsWebSocket
      RouteKey: $disconnect
      AuthorizationType: NONE
      Target: !Join
        - /
        - - integrations
          - !Ref WebSocketDisconnectIntegration

  WebSocketConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref PairingsWebSocket
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketConnectFunction.Arn}/invocations'

  WebSocketDisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref PairingsWebSocket
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketDisconnectFunction.Arn}/invocations'

  WebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - WebSocketConnectRoute
      - WebSocketDisconnectRoute
    Properties:
      ApiId: !Ref PairingsWebSocket

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: prod
      DeploymentId: !Ref WebSocketDeployment
      ApiId: !Ref PairingsWebSocket

  # Lambda Permissions for WebSocket
  WebSocketConnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebSocketConnectFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PairingsWebSocket}/*'

  WebSocketDisconnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebSocketDisconnectFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PairingsWebSocket}/*'

Outputs:
  RestApiUrl:
    Description: REST API endpoint URL
    Value: !Sub 'https://${PairingsApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
  WebSocketUrl:
    Description: WebSocket API endpoint URL
    Value: !Sub 'wss://${PairingsWebSocket}.execute-api.${AWS::Region}.amazonaws.com/prod'
  PairingsTableName:
    Description: DynamoDB Pairings Table Name
    Value: icup-pairings
  RevealStateTableName:
    Description: DynamoDB Reveal State Table Name
    Value: icup-reveal-state

